### ISSUE TITLE
2 Unresolved externals on Windows

### ISSUE THREAD

**Issue by bamfbamf** [fabiensanglard/Chocolate-Wolfenstein-3D#22]
After `Getting SDL-1.2.15` and `Getting SDL_mixer 1.2.12` steps I get this in Visual Studio 2017:
![image](https://user-images.githubusercontent.com/6218809/53918829-5e09fc80-4068-11e9-9fc2-7715d1e0ca41.png)

So it doesn't compile. Any ideas what can be wrong?

**Comment by fabiensanglard** [comment]
The linked cannot find the symbols. You need to add the .a and .lib to the
project.

**Comment by bamfbamf** [comment]
They were linked. But I found [this](https://stackoverflow.com/questions/28247992/how-to-fix-unresolved-externals-of-sdl-2-0-3-on-visual-studio-2015-preview) topic and it helped. I didn't launched anything but it compiles now. 
Steps:
- downloaded `SDL-1.2.15.zip` from [this](https://www.libsdl.org/download-1.2.php) page
- compiled solution in `VisualC` directory, which is for version 6 of VS. The one in `VisualCE` is to old.
- replaced old `SDL.dll`, `SDL.lib` and `SDLmain.lib` and `include` dir with those from compiled version

**Comment by bamfbamf** [comment]
It seems it's alive 
![image](https://user-images.githubusercontent.com/6218809/53929654-c53aa780-408e-11e9-8ea0-f656f34ce114.png)

**Comment by fabiensanglard** [comment]
\o/
